### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Altamash347** [DavidFlashCZ/FlashItem2#1]
Can u tell me how to use this plugin?                                 , Update the Description

will the items have a UI?

**Comment by DavidFlashCZ** [comment]
> Can u tell me how to use this plugin?                                 , Update the Description
> 
> 
> 
> will the items have a UI?
> 
> 

Hey, thank you for asking! I will update the description as soon as I can. FlashItem2 is update FlashItem. After you download it a new configuration file will appear. There are almost all the details. You can set the custom item’s ID, Custom Name and even if you want to give the item to player when he joins the server. When you click a menu will appear (UI). It is fully customizable and no ads included in it. For further questions, ask. Have a great day :)

**Comment by Altamash347** [comment]
Thank you so much for your answer, you are very active. And this plugin is ready for release so please release it so more people will know about this cool and best plugin ever
